### ISSUE TITLE
Need to able to input and retrieve bin edges in 1D spectrum object

### ISSUE THREAD

**Issue by DanRyanIrish** [nmearl/specutils#11]
For X-ray and gamma ray (and possibly other applications) a user of the Spectrum1D object needs to be able to enter bin edges as an array of length n+1, rather than just s spectral axis of length, n, where n is the number of y/flux/counts values.  Example:
``` spectrum1D(flux=flux, bin_edges=bin_edges)```

There also needs to be a way of accessing the bin edges as a Quantity, e.g. 
```spectrum1D.bin_edges()```

This may be done via a wcs object but however it's done the implementation should preferably be invisible to the user.

**Comment by nmearl** [comment]
The `specutils` repo has moved to [`astropy/specutils`](https://github.com/astropy/specutils). Please re-open this issue [on that repo](https://github.com/astropy/specutils/issues). Thanks!
