### ISSUE TITLE
some tests failing due to tests.helpers

### ISSUE THREAD

**Issue by kelle** [nmearl/specutils#20]
https://travis-ci.org/nmearl/specutils/jobs/225349170#L283

maybe @eteq or @adrn can shed some light?

**Comment by bsipocz** [comment]
I'll try to look at this and sort it out during pyastro, the latest.

**Comment by kelle** [comment]
I'd be interested in learning more about this.

**Comment by bsipocz** [comment]
Let's do this next week then. I guess something is not copied over properly from the template, so getting to the bottom of this will be the fastest with a trial and error approach.

**Comment by nmearl** [comment]
The `specutils` repo has moved to [`astropy/specutils`](https://github.com/astropy/specutils). Please re-open this issue [on that repo](https://github.com/astropy/specutils/issues). Thanks!

**Comment by bsipocz** [comment]
I'll have a half working branch for this, will open a PR soon with the fix rather than reopening the issue.
