### ISSUE TITLE
restfreq/restwav

### ISSUE THREAD

**Issue by teuben** [nmearl/specutils#5]
After I created a Spectrum1D using my custom loader:

s3 = Spectrum1D.read(fitsfile, format="cubetest1")

which natively gives me a spectrum in Hz, the wcs has a restfreq, but when switching to a km/s axis, had to do the cumbersome self referencing

s3.to_dispersion("km/s", rest = Quantity(s3.wcs.wcs.restfrq,"Hz")

should the default for rest= not be the one that was found in the wcs as I created it?

**Comment by keflavich** [comment]
@teuben Yes, that is what should happen, and this was probably resolved by #4

**Comment by nmearl** [comment]
The `specutils` repo has moved to [`astropy/specutils`](https://github.com/astropy/specutils). Please re-open this issue [on that repo](https://github.com/astropy/specutils/issues). Thanks!
